### ISSUE TITLE
DTSTART and RDATE throw an error

### ISSUE THREAD

**Issue by AntJanus** [petropavel13/pg_rrule#11]
I'm using pg_rrule to populate a database with dates. Here's a sample RRULE:

```
FREQ=WEEKLY;INTERVAL=5;UNTIL=20200906T050000Z;DTSTART=20160906T050000Z
```

I get an error `MALFORMEDDATA`. I tried substituting `DTSTART` with `RDATE` but get the same error. NO clue where to go from here.

@petropavel13 I saw another user mention this issue in #7

**Comment by petropavel13** [comment]
which version of libical you're using? did you try with libical 2.0? this fork https://github.com/Falmarri/pg_rrule works with libical 2.0

**Comment by AntJanus** [comment]
I'd rather not use a fork but will if that's the only choice. I'm building `pg_rrule` from scratch from the master branch.

I have a question however, and this might give me the ability to choice filter out `DTSTART` from the ruleset and store it separately, when using something like `get_occurrences`, is the second parameter pretty much a `dtstart` equivalent?

**Comment by petropavel13** [comment]
yes. you can use `get_occurrences(rrule, timestamp with time zone)` instead of `DTSTART`

**Comment by AntJanus** [comment]
awesome, thanks!
