### ISSUE TITLE
DTSTART causes error 

### ISSUE THREAD

**Issue by sleistner** [petropavel13/pg_rrule#7]
Defining the following rule
`FREQ=DAILY;DTSTART=20151130T230000Z;UNTIL=20151204T230000Z;WKST=WE;BYDAY=TU,TH`

causes
> MALFORMEDDATA: An input string was not correctly formed or a component has missing or extra properties

Seems `DTSTART` is causing the issue.

**Comment by yolissa** [comment]
Hi ! I currently have the same issue. How did you fix it ?

**Comment by sleistner** [comment]
Hi, I didn't fix it

**Comment by AntJanus** [comment]
What did you do then?
